---
title: "Timeline"
description: |
  questionnaire
author:
  - name: J체rgen Schneider
    url: https://uni-tuebingen.de/de/28915
    affiliation: University of T체bingen
date: "`r Sys.Date()`"
output: radix::radix_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

``` {r, layout="l-screen"}
library(timevis)

projectplan <- data.frame(
    content = c("Linz", "Flensburg", "Stuttgart, <br /> Vechta, T체bingen", 
                "EFA > <br />Itemselektion", "Erstellung<br />neuer FB", 
                "alle Standorte", 
                "CFA > <br />Reliabilit채ten"),
    start = c("2019-03-04", "2019-03-11", "2019-04-01",
              "2019-04-21", "2019-04-30", 
              "2019-05-06", 
              "2019-05-26"),
    end = c("2019-04-21", "2019-04-21", "2019-04-21", 
            "2019-04-29", "2019-05-06", 
            "2019-05-26", 
            "2019-06-09"),
    group = c(rep("er1", 3), rep("aus1", 2), "er2", "aus2"),
    type = c(rep("range", 7))
)

projectgroups <- data.frame(
    id = c("er1", "aus1", "er2", "aus2"),
    content = c("Erhebung I<br />N=200", "Auswertung I", "Erhebung II<br />N=200", "Auswertung II") 
)


timevis(data = projectplan, groups = projectgroups, options = list(editable = F))
# different options like tool tips?
```